name: Push CI

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Codecademy/run-on-yarn@v1
      - run: yarn compile
      - run: yarn build

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: Codecademy/run-on-yarn@v1
      - run: yarn ${{ matrix.command }}

    strategy:
      fail-fast: false
      matrix:
        command: ["format:verify", "lint", "test:ci"]

on: push
